import type { EntityInstance, LegacyAlarmMigrationCandidate } from '../../api/client'

interface Props { candidates: LegacyAlarmMigrationCandidate[]; entities: EntityInstance[]; selections: Record<string, string>; onSelectionChange: (kind: LegacyAlarmMigrationCandidate['source_kind'], key: string, id: string) => void; onMigrate: () => void; migrating: boolean }
const severity: Record<string, string> = { CRITICAL: '严重', MAJOR: '重要', WARNING: '警告', INFO: '提示' }
const operator: Record<string, string> = { gt: '大于', gte: '大于等于', lt: '小于', lte: '小于等于', eq: '等于', ne: '不等于' }
const blockerText: Record<string, string> = { ALARM_MIGRATION_AMBIGUOUS: '需要确认实体实例。', ALARM_ENTITY_UNRESOLVED: '未找到可用的已确认实体实例。', ALARM_FAULT_MAP_UNRESOLVED: '故障映射无法确认。', ALARM_LEGACY_RULE_UNSUPPORTED: '旧规则无法安全转换。', ALARM_MIGRATION_SELECTION_INVALID: '所选实体实例不可用于此配置。', ALARM_SEVERITY_INVALID: '旧配置的严重度无效。' }
const condition = (value: { operator: string; value: unknown }) => `${operator[value.operator] || '比较'} ${String(value.value)}`
const reason = (code: string) => blockerText[code] || '配置存在阻断，请查看诊断信息。'

export default function LegacyMigrationPanel({ candidates, entities, selections, onSelectionChange, onMigrate, migrating }: Props) {
  const names = new Map(entities.map((item) => [item.id, `${item.device_display_name} / ${item.display_name}`]))
  const ambiguous = (candidate: LegacyAlarmMigrationCandidate) => candidate.blockers.some((blocker) => blocker.code === 'ALARM_MIGRATION_AMBIGUOUS')
  const validChoice = (candidate: LegacyAlarmMigrationCandidate) => {
    const selected = selections[`${candidate.source_kind}:${candidate.source_key}`]
    return Boolean(selected && candidate.entity_instance_candidates.includes(selected))
  }
  const blocked = candidates.some((candidate) => candidate.status === 'blocked' && (!ambiguous(candidate) || candidate.blockers.length !== 1 || !validChoice(candidate)))
  return <section aria-labelledby="legacy-migration-heading" className="neu-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id="legacy-migration-heading" className="text-sm font-bold text-gray-800">旧配置迁移</h3><p className="mt-0.5 text-xs text-gray-500">旧配置只读。仅“需要确认实体”的阻断项可通过明确选择后提交。</p></div><button type="button" onClick={onMigrate} disabled={migrating || !candidates.length || blocked} className="neu-btn px-3 py-1.5 text-xs font-medium text-[#287c12] disabled:opacity-50">{migrating ? '迁移中...' : blocked ? '处理阻断项后可迁移' : '执行迁移'}</button></div>{!candidates.length ? <p className="mt-4 text-center text-xs text-gray-400">没有待迁移的旧告警配置。</p> : <div className="mt-3 space-y-2">{candidates.map((candidate) => { const key = `${candidate.source_kind}:${candidate.source_key}`; const selected = selections[key] || candidate.entity_instance_id || ''; const needsSelection = ambiguous(candidate); const proposal = candidate.proposed_rules.find((item) => item.entity_instance_id === selected)?.proposed_rule || (!needsSelection && candidate.proposed_rules.length === 1 ? candidate.proposed_rules[0].proposed_rule : candidate.proposed_rule); return <article key={key} className="rounded border border-white/70 p-3 text-xs"><div className="flex flex-wrap justify-between gap-2"><strong className="text-gray-800">{candidate.display_name || '旧告警配置'}</strong><span className={candidate.status === 'migrated' ? 'text-[#287c12]' : candidate.status === 'ready' ? 'text-[#287c12]' : 'text-amber-800'}>{candidate.status === 'migrated' ? '已完成' : candidate.status === 'ready' ? '可迁移' : '需要处理'}</span></div><p className="mt-1 text-gray-600">拟定规则：{proposal ? `${proposal.name}，${severity[proposal.severity]}，触发${condition(proposal.trigger)}，恢复${condition(proposal.recovery)}` : needsSelection ? '请选择实体实例后查看对应规则。' : '无法生成拟定规则'}</p>{needsSelection ? <label className="mt-2 block text-gray-700">确认实体实例<select value={selected} onChange={(event) => onSelectionChange(candidate.source_kind, candidate.source_key, event.target.value)} className="neu-input mt-1 block w-full px-2 py-1"><option value="">请选择实体实例</option>{candidate.entity_instance_candidates.map((id) => <option key={id} value={id}>{names.get(id) || '已确认实体实例'}</option>)}</select></label> : selected ? <p className="mt-1 text-gray-600">关联实体：{names.get(selected) || '已确认实体实例'}</p> : null}{candidate.blockers.map((blocker) => <p key={blocker.code} data-diagnostic={blocker.message} className="mt-1 text-amber-800">{reason(blocker.code)}</p>)}</article> })}</div>}</section>
}
