import { useMemo, useState } from 'react'
import type { AlarmBlocker, AlarmConfigurationPlan, AlarmConfigurationPlanItem, AlarmPlanAction } from '../../api/client'

interface Props { plan: AlarmConfigurationPlan; entityNames: Map<string, string>; applying: boolean; stale: boolean; onApply: () => void }
const actions: { value: AlarmPlanAction; label: string }[] = [{ value: 'add', label: '新增' }, { value: 'update', label: '更新' }, { value: 'preserve', label: '保留' }, { value: 'delete_candidate', label: '删除候选' }, { value: 'block', label: '阻断' }]
const blockerText: Record<string, string> = { ALARM_ENTITY_UNRESOLVED: '实体实例未确认或不可用。', ALARM_DATA_TYPE_UNSUPPORTED: '实体数据类型不支持该比较。', ALARM_UNIT_MISMATCH: '规则单位与实体单位不一致。', ALARM_SEVERITY_INVALID: '严重度无效。', ALARM_THRESHOLD_INVALID: '触发与恢复条件不成立。' }
function reason(blocker: AlarmBlocker) { return blockerText[blocker.code] || '配置存在阻断，请查看诊断信息。' }

export default function PlanPreview({ plan, entityNames, applying, stale, onApply }: Props) {
  const [filter, setFilter] = useState<'all' | AlarmPlanAction>('all'); const [page, setPage] = useState(1)
  const counts = useMemo(() => Object.fromEntries(actions.map(({ value }) => [value, plan.items.filter((item) => item.action === value).length])) as Record<AlarmPlanAction, number>, [plan.items])
  const blockers = useMemo(() => Array.from(new Map([...plan.blockers, ...plan.items.flatMap((item) => item.blockers)].map((item) => [item.code, item])).values()), [plan])
  const items = filter === 'all' ? plan.items : plan.items.filter((item) => item.action === filter); const pages = Math.max(1, Math.ceil(items.length / 100)); const visible = items.slice((page - 1) * 100, page * 100)
  const blocked = plan.status === 'blocked' || blockers.length > 0
  const empty = plan.items.length === 0
  const actionText = (item: AlarmConfigurationPlanItem) => item.action === 'delete_candidate' ? '应用后停用新触发' : actions.find((entry) => entry.value === item.action)?.label || '待处理'
  return <section aria-labelledby="alarm-plan-heading" className="neu-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id="alarm-plan-heading" className="text-sm font-bold text-gray-800">变更预览</h3><p className="mt-0.5 text-xs text-gray-500">本计划展开 {plan.items.length.toLocaleString()} 项定义变更，应用前不会写入现场配置。</p></div><button type="button" onClick={onApply} disabled={empty || blocked || stale || applying} className="rounded-lg bg-[#52c41a] px-4 py-2 text-xs font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{applying ? '正在应用...' : stale ? '计划已失效，请重新生成' : blocked ? '存在阻断项' : empty ? '没有可应用的变更' : '确认应用配置'}</button></div>
    {(empty || blocked || stale) && <div role="alert" className="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-900">{stale ? '配置基线已变化，请重新生成并确认计划。' : empty ? '计划不包含任何变更，不能应用。' : blockers.map(reason).join(' ')}</div>}
    <div className="mt-3 flex flex-wrap gap-2"><button type="button" aria-pressed={filter === 'all'} onClick={() => { setFilter('all'); setPage(1) }} className="rounded border px-2 py-1 text-xs">全部 {plan.items.length}</button>{actions.map(({ value, label }) => <button key={value} type="button" aria-pressed={filter === value} onClick={() => { setFilter(value); setPage(1) }} className="rounded border px-2 py-1 text-xs">{label} {counts[value]}</button>)}</div>
    <div className="mt-3 space-y-2 md:hidden">{visible.map((item, index) => <article key={`${item.entity_instance_id}-${item.rule_id}-${index}`} className="rounded border border-white/70 p-3 text-xs"><div className="font-medium text-gray-800">{entityNames.get(item.entity_instance_id) || '已选实体实例'}</div><div className="mt-1 text-gray-600">规则：{item.rule_id}　动作：{actionText(item)}</div>{item.action === 'delete_candidate' && <p className="mt-1 text-amber-800">应用后停用新触发；历史事件与审计证据保留。</p>}{item.blockers.map((blocker) => <p key={blocker.code} className="mt-1 text-amber-800">{reason(blocker)}</p>)}</article>)}</div>
    <div className="mt-3 hidden overflow-auto rounded-lg border border-white/70 md:block"><table className="w-full text-left text-xs"><thead className="bg-white/20 text-[11px] text-gray-500"><tr><th className="px-3 py-2">实体实例</th><th className="px-3 py-2">规则</th><th className="px-3 py-2">动作</th><th className="px-3 py-2">状态</th></tr></thead><tbody>{visible.map((item, index) => <tr key={`${item.entity_instance_id}-${item.rule_id}-${index}`} className="border-t border-white/70"><td className="px-3 py-2">{entityNames.get(item.entity_instance_id) || '已选实体实例'}</td><td className="px-3 py-2">{item.rule_id}</td><td className="px-3 py-2">{actionText(item)}</td><td className="px-3 py-2">{item.action === 'delete_candidate' ? '停用新触发；保留历史证据' : item.blockers.map(reason).join(' ') || '可处理'}</td></tr>)}</tbody></table></div>
    {items.length > 100 && <div className="mt-3 flex items-center justify-end gap-2 text-xs"><button type="button" className="neu-btn px-2 py-1" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>上一页</button><span>{page} / {pages}</span><button type="button" className="neu-btn px-2 py-1" disabled={page === pages} onClick={() => setPage((value) => value + 1)}>下一页</button></div>}
  </section>
}
